### PR TITLE
port pip to poetry

### PR DESCRIPTION
**Pull request by Aakritisingh9971**
ported pip to poetry

### CODE REVIEW

**Review by newtectonics — CHANGES_REQUESTED** [review]
We don't want to get rid of pip for this, it's the standard way to install dependencies. I'd be find supporting other technologies. does this still let pip work? also this breaks documentation by deleting requirements.txt

**Comment by Aakritisingh9971** [comment]
hey i have updated the documentation for the same, here's the link [https://app.gitbook.com/o/V8ATumblv0Fr9pyDj72K/s/klyjkARA5tDIZfm335fU/~/changes/PN6tNN9ymLAgev932mGR/getting-started/installation-and-setup]
and as poetry is the modern package manager so it would be easier for people to manage and install dependencies of python project going forward. does this sound good to you?

**Comment by leafyoung** [comment]
Poetry is modern but we shall not throw pip away.

**Comment by abhishektvz** [comment]
@leafyoung pyproject.toml can be common to both pip and poetry https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/

**Comment by leafyoung** [comment]
The current project file missed "git+https://github.com/credmark/credmark-model-framework-py.git@0.8.10". How to include this?

**Comment by abhishektvz** [comment]
> The current project file missed "git+https://github.com/credmark/credmark-model-framework-py.git@0.8.10". How to include this?

Updated pyproject.toml and tested by installing using both pip and poetry,
The new commit now let's us move to pyproject.toml as the single source for build dependency and metadata management

**Comment by newtectonics** [comment]
@iwyrkore @leafyoung can I get some input on this? I don't know enough about `poetry` to make a call.

**Comment by leafyoung** [comment]
I am fine with the update now. It will still keep pip around with `pip install .`. The transition is smooth.

image

**Comment by iwyrkore** [comment]
Before this is merged, make sure with @iwyrkore that the build repo is updated.

**Comment by leafyoung** [comment]
I am conducting more testing on this commit.
As my earlier test, there were some packages unmet for the versions. There might need some version change in framework's requirement.txt.

**Comment by iwyrkore** [comment]
I'm getting an error when i run  `pip install .`

```
        raise ModuleOrPackageNotFound(
    poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package credmark-models-py
```

Remind me why we are doing this again? This is not a package that needs to get installed. There is no metadata etc. There is just 2 requirements files -- nothing complicated. We've already spent many hours on this and it gains us nothing.

**Comment by leafyoung** [comment]
The commit [746ed57](https://github.com/credmark/credmark-models-py/pull/51/commits/746ed5704fcf29bea0d3966ebd19e47ba223fc57) was to exclude installation of models-py itself so we could use `pip install .`, not `pip install -e .` but it does not. It did not work out with either Python 3.9 or 3.10.

I am actually fine with the extra `-e`. There could be some long-term benefits of this transition so I am still for this transition.

Two things left
- add back the `packages = [{ include = "models" }]` in pyproject.toml
- Github action needs change to install the dev dependencies, now missing pylint.

**Comment by newtectonics** [comment]
We've talked internally, since this isn't a package: it doesn't need to be installed itself. We're gonna skip poetry, since its not the standard at the moment. Subject to change down the road.

**Pull request closed without merging**
